2025-09-16 17:03:17	WARN	sdcal::calibrater::setvi(bool,bool)	Already using OLD VisibilityIterator.
2025-09-16 17:03:18	SEVERE	sdcal::::casa	Traceback (most recent call last):
2025-09-16 17:03:18	SEVERE	sdcal::::casa+	             ^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:03:18	SEVERE	sdcal::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdcal.py", line 78, in sdcal
2025-09-16 17:03:18	SEVERE	sdcal::::casa+	    raise Exception('Applytable name must be specified.')
2025-09-16 17:03:18	SEVERE	sdcal::::casa+	Exception: Applytable name must be specified.
2025-09-16 17:03:18	SEVERE	sdcal::::casa	Applytable name must be specified.
2025-09-16 17:03:18	SEVERE	sdcal::::casa	Task sdcal raised an exception of class Exception with the following message: Applytable name must be specified.
