2025-09-16 17:01:27	SEVERE	sdbaseline::::casa	Traceback (most recent call last):
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	             ^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdbaseline.py", line 54, in sdbaseline
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	    temp_outfile = _do_fit(infile, datacolumn, antenna, field, spw, timerange, scan,
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdbaseline.py", line 512, in _do_fit
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	    check_fftthresh(fftthresh)
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdbaseline.py", line 376, in check_fftthresh
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	    raise ValueError('fftthresh must be float or integer or string.')
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa+	ValueError: fftthresh must be float or integer or string.
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa	fftthresh must be float or integer or string.
2025-09-16 17:01:27	SEVERE	sdbaseline::::casa	Task sdbaseline raised an exception of class ValueError with the following message: fftthresh must be float or integer or string.
