{"name": "test_wrong_field_select_data", "status": "passed", "description": "\n          test_wrong_field: should produce exception in selectData.\n\n          Exception like:\n            RuntimeError: Error in selectData() : Field Expression: Partial or no match for Field ID list [33]\n          ", "attachments": [{"name": "stderr", "source": "0789861b-47c3-4bf0-b3a5-996f8b262188-attachment.txt", "type": "text/plain"}], "start": 1758048190118, "stop": 1758048190213, "uuid": "cece322a-a8ce-4a2d-9d66-d4f9f832041f", "historyId": "1a8d2660c78f76c9e63efc4de9e7f370", "testCaseId": "1a8d2660c78f76c9e63efc4de9e7f370", "fullName": "casatasks.test_task_tclean.test_errors_failures#test_wrong_field_select_data", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_tclean"}, {"name": "subSuite", "value": "test_errors_failures"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_tclean"}], "titlePath": ["casatasks", "test_task_tclean.py", "test_errors_failures"]}