2025-09-16 17:01:26	SEVERE	sdbaseline::::casa	Traceback (most recent call last):
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	             ^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdbaseline.py", line 54, in sdbaseline
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	    temp_outfile = _do_fit(infile, datacolumn, antenna, field, spw, timerange, scan,
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdbaseline.py", line 510, in _do_fit
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	    addwn = parse_wavenumber_param(addwn)
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdbaseline.py", line 283, in parse_wavenumber_param
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	    elif wn[0] == '<':
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	         ~~^^^
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa+	IndexError: string index out of range
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa	string index out of range
2025-09-16 17:01:26	SEVERE	sdbaseline::::casa	Task sdbaseline raised an exception of class IndexError with the following message: string index out of range
